In [4]:
import torch

# Your input tensors
embeddings = torch.randn(2, 3, 10)  # Replace with your actual tensor
is_special = torch.tensor([[True, False, True], [False, True, False]])  # Replace with your actual bool tensor

# Create a mask to apply either 1 or 2 to the embeddings
mask = torch.where(is_special.unsqueeze(-1), torch.tensor(1.0), torch.tensor(2.0))

# Broadcast the mask to match the shape of the embeddings tensor
mask = mask.expand_as(embeddings)
print(f"Mask {mask.shape}\n {mask}")

# Element-wise multiplication to update the embeddings
updated_embeddings = embeddings * mask


Mask torch.Size([2, 3, 10])
 tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]]])


In [10]:
import torch

# Sample data
batch_size = 4
sequence_length = 5
embedding_length = 10

# Create random tensors for X and M
X = torch.randn(batch_size, sequence_length, embedding_length)
M = torch.randint(0, 2, (batch_size, sequence_length), dtype=torch.bool)
M_values = torch.randint(1, 4, (batch_size, sequence_length))

print(M)
print(M_values)


tensor([[ True, False,  True, False,  True],
        [False, False,  True,  True,  True],
        [ True,  True, False,  True, False],
        [False, False, False,  True,  True]])
tensor([[3, 1, 3, 1, 3],
        [1, 3, 2, 1, 3],
        [3, 1, 2, 1, 1],
        [1, 1, 3, 2, 3]])


In [27]:
import torch

# Sample data
batch_size = 1
sequence_length = 10
embedding_length = 5

# Create random tensors for X and M
X = torch.randn(batch_size, sequence_length, embedding_length)
M = torch.randint(0, 2, (batch_size, sequence_length), dtype=torch.bool)
print(M)

tensor([[False,  True,  True, False, False,  True, False, False, False, False]])


In [35]:
# Initialize variables
EM = torch.randint(0, 2, (batch_size, sequence_length), dtype=torch.bool)

result = []
current_map = {}
current_tensor = None  # Variable to accumulate consecutive True values
start = (0,0)
# Iterate through the M tensor
for i in range(batch_size):
    for j in range(sequence_length):
        if M[i][j]:
            if current_tensor is None:
                current_map["start"] = (i, j)
                current_map["encoder_tensor"]  = EM[i][j]
                current_tensor = X[i][j].unsqueeze(0)  # Create a new tensor
            else:
                current_tensor = torch.cat((current_tensor, X[i][j].unsqueeze(0)), dim=0)
        elif current_tensor is not None:
            current_map["end"] = (i, j-1)
            current_map["tensor_list"] = current_tensor
            result.append(current_map)
            current_tensor = None
            current_map = {}

    if current_tensor is not None:
            current_map["end"] = (i, sequence_length)
            current_map["tensor_list"] = current_tensor
            result.append(current_map)
            current_tensor = None
            current_map = {}

# Print the list of resulting tensors
for i, item in enumerate(result):
    print(f"Tensor {i + 1} shape:", item.get("tensor_list").shape,
          "Start: ", item.get("start"), "End: ", item.get("end"), item.get("encoder_tensor") )

Tensor 1 shape: torch.Size([2, 5]) Start:  (0, 1) End:  (0, 2) tensor(False)
Tensor 2 shape: torch.Size([1, 5]) Start:  (0, 5) End:  (0, 5) tensor(False)


In [15]:
original_list = [1, 2, 3, 4, 5]
new_list = [(item+1, item+2) for item in original_list]
print(new_list)

[(2, 3), (3, 4), (4, 5), (5, 6), (6, 7)]


In [17]:
original_list = [1, 2, 3, 4, 5]

# Add both item and item*2 to the new list
new_list = [item for item in original_list for _ in range(2)]
print(new_list)

[1, 1, 2, 2, 3, 3, 4, 4, 5, 5]


In [21]:
my_bool = [True]

tensor_bool = torch.tensor(my_bool, dtype=torch.bool)
tensor_bool_one = torch.tensor([False], dtype=torch.bool)

concatenated_tensor = torch.cat((tensor_bool, tensor_bool_one), dim=0)

print(concatenated_tensor)

tensor([ True, False])


In [34]:
first_dim_size = M.size(0)
print(first_dim_size)

1


In [37]:
import torch

# Sample tensor of shape [batch_size, sequence_length, hidden_dim]
batch_size = 3
sequence_length = 10
hidden_dim = 5
original_tensor = torch.randn(batch_size, sequence_length, hidden_dim)

# Specify the batch number and the slice window
batch_index = 1  # Replace a slice in the 2nd batch
start_sequence = 3
end_sequence = 7

# Create a tensor to replace the slice with
replacement_tensor = torch.ones(end_sequence - start_sequence, hidden_dim)

# Replace the slice in the original tensor
original_tensor[batch_index, start_sequence:end_sequence, :] = replacement_tensor

# Print the updated tensor
print(original_tensor)


tensor([[[ 0.1591, -0.0102,  1.1763, -0.3949,  1.3171],
         [-0.6134, -0.5939, -0.7604,  2.2294, -0.1385],
         [ 0.7342,  2.4203,  0.0426,  0.1816, -0.7072],
         [-0.3910, -0.3756,  0.5061, -0.0571,  1.3809],
         [ 0.4263,  0.9049,  0.7583, -1.0946,  1.2673],
         [-0.0242,  1.7505,  0.0562,  1.2286, -0.5472],
         [ 0.2191, -0.6461,  0.9158, -1.9531, -1.1377],
         [-0.0860, -0.8652, -1.7684,  0.3371, -0.5477],
         [ 1.3511,  0.3069, -0.7994,  0.7900,  0.4231],
         [ 1.1680, -0.4623,  1.7892,  0.9823,  0.4738]],

        [[-0.8528,  2.4968, -0.3063, -0.3109, -0.4799],
         [ 1.1040,  0.0427, -1.7871,  0.0991, -0.1991],
         [-0.7583,  0.5084, -0.2497, -0.5880,  0.4240],
         [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
         [-0.7509,  1.1820,  1.1245,  0.8561, 

In [3]:
my_dict = {
    "joaa": 100,
    "prattoy": 200,
    "enam": 300
}

# Initializing the output vocabulary items
for index, output_token_classification_head_vocab_item in my_dict.items():
    output_vocabulary_item = {
        "OutputVocabBuilder.OUTPUT_TOKEN_CLASSIFICATION_HEAD_VOCAB_ITEM": output_token_classification_head_vocab_item,
        "OutputVocabBuilder.INDEX_TO_OUTPUT": {},
        "OutputVocabBuilder.OUTPUT_TO_INDEX": {},
    }
    my_dict[index] = output_vocabulary_item

print(my_dict.items())

dict_items([('joaa', {'OutputVocabBuilder.OUTPUT_TOKEN_CLASSIFICATION_HEAD_VOCAB_ITEM': 100, 'OutputVocabBuilder.INDEX_TO_OUTPUT': {}, 'OutputVocabBuilder.OUTPUT_TO_INDEX': {}}), ('prattoy', {'OutputVocabBuilder.OUTPUT_TOKEN_CLASSIFICATION_HEAD_VOCAB_ITEM': 200, 'OutputVocabBuilder.INDEX_TO_OUTPUT': {}, 'OutputVocabBuilder.OUTPUT_TO_INDEX': {}}), ('enam', {'OutputVocabBuilder.OUTPUT_TOKEN_CLASSIFICATION_HEAD_VOCAB_ITEM': 300, 'OutputVocabBuilder.INDEX_TO_OUTPUT': {}, 'OutputVocabBuilder.OUTPUT_TO_INDEX': {}})])


In [3]:
for i in range(6, 10):
    print(i)


6
7
8
9


In [2]:
lst = [1,2,3,4,5,6,7,8]
for i, item in enumerate(lst, start=6):
    print(f"i value is ${i} and item is ${item}")


i value is $6 and item is $1
i value is $7 and item is $2
i value is $8 and item is $3
i value is $9 and item is $4
i value is $10 and item is $5
i value is $11 and item is $6
i value is $12 and item is $7
i value is $13 and item is $8


In [4]:
def example_function(param1, param2, param3):
    print(f"param1: {param1}, param2: {param2}, param3: {param3}")

# Your list of parameters
param_list = [1, 2, 3, 4, 5, 6]

# Define the indices i and j
i = 2
j = 4

# Extract the relevant portion of the list using slicing
params_to_pass = param_list[i:j+1]

# Call the function with the unpacked parameters
example_function(*params_to_pass)

param1: 3, param2: 4, param3: 5


In [4]:
i = 0
while i <= 10:
    # Your code here
    if i == 3:
        i = 8  # exit the loop when i becomes 8

    print(i)
    i += 1

lst = [1,2,3,4]
print(len(lst))

0
1
2
8
9
10
4
