In [4]:
import torch

# Your input tensors
embeddings = torch.randn(2, 3, 10)  # Replace with your actual tensor
is_special = torch.tensor([[True, False, True], [False, True, False]])  # Replace with your actual bool tensor

# Create a mask to apply either 1 or 2 to the embeddings
mask = torch.where(is_special.unsqueeze(-1), torch.tensor(1.0), torch.tensor(2.0))

# Broadcast the mask to match the shape of the embeddings tensor
mask = mask.expand_as(embeddings)
print(f"Mask {mask.shape}\n {mask}")

# Element-wise multiplication to update the embeddings
updated_embeddings = embeddings * mask


Mask torch.Size([2, 3, 10])
 tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]]])


In [5]:
import torch

# Sample data
batch_size = 4
sequence_length = 5
embedding_length = 10

# Create random tensors for X and M
X = torch.randn(batch_size, sequence_length, embedding_length)
M = torch.randint(0, 2, (batch_size, sequence_length), dtype=torch.bool)
M_values = torch.randint(1, 4, (batch_size, sequence_length))

print(M)
print(M_values)


tensor([[False, False,  True, False, False],
        [ True,  True,  True, False, False],
        [ True, False, False, False,  True],
        [ True, False, False,  True,  True]])
tensor([[2, 1, 3, 3, 2],
        [3, 2, 3, 3, 1],
        [2, 1, 1, 3, 2],
        [1, 3, 3, 1, 2]])


In [6]:
import torch

# Sample data
batch_size = 4
sequence_length = 10
embedding_length = 5

# Create random tensors for X and M
X = torch.randn(batch_size, sequence_length, embedding_length)
M = torch.randint(0, 2, (batch_size, sequence_length), dtype=torch.bool)


In [9]:
# Initialize variables
print(M)

EM = torch.randint(0, 2, (batch_size, sequence_length), dtype=torch.bool)

result = []
current_map = {}
current_tensor = None  # Variable to accumulate consecutive True values
start = (0,0)
# Iterate through the M tensor
for i in range(batch_size):
    for j in range(sequence_length):
        if M[i][j]:
            if current_tensor is None:
                current_map["start"] = (i, j)
                current_map["encoder_tensor"]  = EM[i][j]
                current_tensor = X[i][j].unsqueeze(0)  # Create a new tensor
            else:
                current_tensor = torch.cat((current_tensor, X[i][j].unsqueeze(0)), dim=0)
        elif current_tensor is not None:
            current_map["end"] = (i, j-1)
            current_map["tensor_list"] = current_tensor
            result.append(current_map)
            current_tensor = None
            current_map = {}

    if current_tensor is not None:
            current_map["end"] = (i, sequence_length)
            current_map["tensor_list"] = current_tensor
            result.append(current_map)
            current_tensor = None
            current_map = {}

# Print the list of resulting tensors
for i, item in enumerate(result):
    print(f"Tensor {i + 1} shape:", item.get("tensor_list").shape)

tensor([[ True,  True,  True, False, False, False, False,  True, False, False],
        [False,  True, False,  True,  True, False,  True,  True, False, False],
        [ True,  True,  True,  True, False, False, False, False, False,  True],
        [ True, False, False,  True,  True, False,  True, False,  True,  True]])
Tensor 1 shape: torch.Size([3, 5])
Tensor 2 shape: torch.Size([1, 5])
Tensor 3 shape: torch.Size([1, 5])
Tensor 4 shape: torch.Size([2, 5])
Tensor 5 shape: torch.Size([2, 5])
Tensor 6 shape: torch.Size([4, 5])
Tensor 7 shape: torch.Size([1, 5])
Tensor 8 shape: torch.Size([1, 5])
Tensor 9 shape: torch.Size([2, 5])
Tensor 10 shape: torch.Size([1, 5])
Tensor 11 shape: torch.Size([2, 5])
