In [6]:
import torch

# Your input tensors
embeddings = torch.randn(2, 3, 10)  # Replace with your actual tensor
is_special = torch.tensor([[True, False, True], [False, True, False]])  # Replace with your actual bool tensor

# Create a mask to apply either 1 or 2 to the embeddings
mask = torch.where(is_special.unsqueeze(-1), torch.tensor(1.0), torch.tensor(2.0))

# Broadcast the mask to match the shape of the embeddings tensor
mask = mask.expand_as(embeddings)
print(f"Mask {mask.shape}\n {mask}")

# Element-wise multiplication to update the embeddings
updated_embeddings = embeddings * mask


Mask torch.Size([2, 3, 10])
 tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]]])


In [42]:
import torch

# Existing tensor
input_tensor = torch.tensor([[1, 2]])
print(input_tensor.shape)

# New row to add
new_row = torch.tensor([5, 6])
print(new_row)
un_new_row = new_row.unsqueeze(0)
print(un_new_row)

# Stack the new row below the existing tensor
output_tensor = torch.cat((input_tensor, un_new_row), dim=0)

print(output_tensor)

torch.Size([1, 2])
tensor([5, 6])
tensor([[5, 6]])
tensor([[1, 2],
        [5, 6]])


In [56]:
import torch

# Step 1: Create an empty tensor
# You can use torch.empty to create an uninitialized tensor or torch.zeros to create a tensor filled with zeros.
empty_tensor = torch.empty((0, 3, 2), dtype=torch.float32)  # Create an empty tensor with shape (0, 2)
print(empty_tensor.shape)
# Step 2: Add items to the empty tensor
new_items = torch.tensor([[1, 2], [3,4], [3,4]]).unsqueeze(0)  # New items to add
print(new_items.shape)

# Concatenate the new items to the empty tensor
result = torch.cat((empty_tensor, new_items), dim=0)

print(result)

torch.Size([0, 3, 2])
torch.Size([1, 3, 2])
tensor([[[1., 2.],
         [3., 4.],
         [3., 4.]]])
